/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ATSResult = IDL.Record({
  'missingSections' : IDL.Vec(IDL.Text),
  'suggestions' : IDL.Vec(IDL.Text),
  'textHash' : IDL.Text,
  'score' : IDL.Nat,
  'missingSkills' : IDL.Vec(IDL.Text),
});
export const ProjectEntry = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
});
export const EducationEntry = IDL.Record({
  'field' : IDL.Text,
  'startYear' : IDL.Int,
  'endYear' : IDL.Int,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
});
export const ExperienceEntry = IDL.Record({
  'startYear' : IDL.Int,
  'responsibilities' : IDL.Vec(IDL.Text),
  'endYear' : IDL.Int,
  'company' : IDL.Text,
  'position' : IDL.Text,
});
export const CertificationEntry = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Int,
  'issuer' : IDL.Text,
});
export const Resume = IDL.Record({
  'projects' : IDL.Vec(ProjectEntry),
  'name' : IDL.Text,
  'education' : IDL.Vec(EducationEntry),
  'email' : IDL.Text,
  'experience' : IDL.Vec(ExperienceEntry),
  'summary' : IDL.Text,
  'phone' : IDL.Text,
  'certifications' : IDL.Vec(CertificationEntry),
  'skills' : IDL.Vec(IDL.Text),
});
export const CareerProfile = IDL.Record({
  'readinessScore' : IDL.Nat,
  'completedSteps' : IDL.Vec(IDL.Text),
  'targetRole' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'eligibleRoles' : IDL.Nat,
  'careerReadiness' : IDL.Nat,
  'atsScore' : IDL.Nat,
  'resumeCompletion' : IDL.Nat,
  'missingSkills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteAllUserData' : IDL.Func([IDL.Principal], [], []),
  'getATSResult' : IDL.Func([IDL.Principal], [ATSResult], ['query']),
  'getAggregatedStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'ats' : ATSResult,
          'resume' : Resume,
          'careerProfile' : CareerProfile,
          'dashboardStats' : DashboardStats,
        }),
      ],
      ['query'],
    ),
  'getAllATSResults' : IDL.Func([], [IDL.Vec(ATSResult)], ['query']),
  'getAllCareerProfiles' : IDL.Func([], [IDL.Vec(CareerProfile)], ['query']),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getCareerProfile' : IDL.Func([IDL.Principal], [CareerProfile], ['query']),
  'getDashboardStats' : IDL.Func([IDL.Principal], [DashboardStats], ['query']),
  'getResume' : IDL.Func([IDL.Principal], [Resume], ['query']),
  'getTopReadinessProfiles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CareerProfile)],
      ['query'],
    ),
  'saveATSResult' : IDL.Func([ATSResult], [], []),
  'saveCareerProfile' : IDL.Func([CareerProfile], [], []),
  'saveFullProfile' : IDL.Func([Resume, ATSResult, CareerProfile], [], []),
  'saveResume' : IDL.Func([Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ATSResult = IDL.Record({
    'missingSections' : IDL.Vec(IDL.Text),
    'suggestions' : IDL.Vec(IDL.Text),
    'textHash' : IDL.Text,
    'score' : IDL.Nat,
    'missingSkills' : IDL.Vec(IDL.Text),
  });
  const ProjectEntry = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
  });
  const EducationEntry = IDL.Record({
    'field' : IDL.Text,
    'startYear' : IDL.Int,
    'endYear' : IDL.Int,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
  });
  const ExperienceEntry = IDL.Record({
    'startYear' : IDL.Int,
    'responsibilities' : IDL.Vec(IDL.Text),
    'endYear' : IDL.Int,
    'company' : IDL.Text,
    'position' : IDL.Text,
  });
  const CertificationEntry = IDL.Record({
    'name' : IDL.Text,
    'year' : IDL.Int,
    'issuer' : IDL.Text,
  });
  const Resume = IDL.Record({
    'projects' : IDL.Vec(ProjectEntry),
    'name' : IDL.Text,
    'education' : IDL.Vec(EducationEntry),
    'email' : IDL.Text,
    'experience' : IDL.Vec(ExperienceEntry),
    'summary' : IDL.Text,
    'phone' : IDL.Text,
    'certifications' : IDL.Vec(CertificationEntry),
    'skills' : IDL.Vec(IDL.Text),
  });
  const CareerProfile = IDL.Record({
    'readinessScore' : IDL.Nat,
    'completedSteps' : IDL.Vec(IDL.Text),
    'targetRole' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'eligibleRoles' : IDL.Nat,
    'careerReadiness' : IDL.Nat,
    'atsScore' : IDL.Nat,
    'resumeCompletion' : IDL.Nat,
    'missingSkills' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteAllUserData' : IDL.Func([IDL.Principal], [], []),
    'getATSResult' : IDL.Func([IDL.Principal], [ATSResult], ['query']),
    'getAggregatedStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'ats' : ATSResult,
            'resume' : Resume,
            'careerProfile' : CareerProfile,
            'dashboardStats' : DashboardStats,
          }),
        ],
        ['query'],
      ),
    'getAllATSResults' : IDL.Func([], [IDL.Vec(ATSResult)], ['query']),
    'getAllCareerProfiles' : IDL.Func([], [IDL.Vec(CareerProfile)], ['query']),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getCareerProfile' : IDL.Func([IDL.Principal], [CareerProfile], ['query']),
    'getDashboardStats' : IDL.Func(
        [IDL.Principal],
        [DashboardStats],
        ['query'],
      ),
    'getResume' : IDL.Func([IDL.Principal], [Resume], ['query']),
    'getTopReadinessProfiles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CareerProfile)],
        ['query'],
      ),
    'saveATSResult' : IDL.Func([ATSResult], [], []),
    'saveCareerProfile' : IDL.Func([CareerProfile], [], []),
    'saveFullProfile' : IDL.Func([Resume, ATSResult, CareerProfile], [], []),
    'saveResume' : IDL.Func([Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };