/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ATSResult {
  'missingSections' : Array<string>,
  'suggestions' : Array<string>,
  'textHash' : string,
  'score' : bigint,
  'missingSkills' : Array<string>,
}
export interface CareerProfile {
  'readinessScore' : bigint,
  'completedSteps' : Array<string>,
  'targetRole' : string,
}
export interface CertificationEntry {
  'name' : string,
  'year' : bigint,
  'issuer' : string,
}
export interface DashboardStats {
  'eligibleRoles' : bigint,
  'careerReadiness' : bigint,
  'atsScore' : bigint,
  'resumeCompletion' : bigint,
  'missingSkills' : bigint,
}
export interface EducationEntry {
  'field' : string,
  'startYear' : bigint,
  'endYear' : bigint,
  'institution' : string,
  'degree' : string,
}
export interface ExperienceEntry {
  'startYear' : bigint,
  'responsibilities' : Array<string>,
  'endYear' : bigint,
  'company' : string,
  'position' : string,
}
export interface ProjectEntry {
  'name' : string,
  'description' : string,
  'technologies' : Array<string>,
}
export interface Resume {
  'projects' : Array<ProjectEntry>,
  'name' : string,
  'education' : Array<EducationEntry>,
  'email' : string,
  'experience' : Array<ExperienceEntry>,
  'summary' : string,
  'phone' : string,
  'certifications' : Array<CertificationEntry>,
  'skills' : Array<string>,
}
export interface _SERVICE {
  'deleteAllUserData' : ActorMethod<[Principal], undefined>,
  'getATSResult' : ActorMethod<[Principal], ATSResult>,
  'getAggregatedStats' : ActorMethod<
    [Principal],
    {
      'ats' : ATSResult,
      'resume' : Resume,
      'careerProfile' : CareerProfile,
      'dashboardStats' : DashboardStats,
    }
  >,
  'getAllATSResults' : ActorMethod<[], Array<ATSResult>>,
  'getAllCareerProfiles' : ActorMethod<[], Array<CareerProfile>>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getCareerProfile' : ActorMethod<[Principal], CareerProfile>,
  'getDashboardStats' : ActorMethod<[Principal], DashboardStats>,
  'getResume' : ActorMethod<[Principal], Resume>,
  'getTopReadinessProfiles' : ActorMethod<[bigint], Array<CareerProfile>>,
  'saveATSResult' : ActorMethod<[ATSResult], undefined>,
  'saveCareerProfile' : ActorMethod<[CareerProfile], undefined>,
  'saveFullProfile' : ActorMethod<
    [Resume, ATSResult, CareerProfile],
    undefined
  >,
  'saveResume' : ActorMethod<[Resume], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];