/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardStats {
    eligibleRoles: bigint;
    careerReadiness: bigint;
    atsScore: bigint;
    resumeCompletion: bigint;
    missingSkills: bigint;
}
export interface ATSResult {
    missingSections: Array<string>;
    suggestions: Array<string>;
    textHash: string;
    score: bigint;
    missingSkills: Array<string>;
}
export interface CertificationEntry {
    name: string;
    year: bigint;
    issuer: string;
}
export interface Resume {
    projects: Array<ProjectEntry>;
    name: string;
    education: Array<EducationEntry>;
    email: string;
    experience: Array<ExperienceEntry>;
    summary: string;
    phone: string;
    certifications: Array<CertificationEntry>;
    skills: Array<string>;
}
export interface ExperienceEntry {
    startYear: bigint;
    responsibilities: Array<string>;
    endYear: bigint;
    company: string;
    position: string;
}
export interface CareerProfile {
    readinessScore: bigint;
    completedSteps: Array<string>;
    targetRole: string;
}
export interface ProjectEntry {
    name: string;
    description: string;
    technologies: Array<string>;
}
export interface EducationEntry {
    field: string;
    startYear: bigint;
    endYear: bigint;
    institution: string;
    degree: string;
}
export interface backendInterface {
    deleteAllUserData(user: Principal): Promise<void>;
    getATSResult(user: Principal): Promise<ATSResult>;
    getAggregatedStats(user: Principal): Promise<{
        ats: ATSResult;
        resume: Resume;
        careerProfile: CareerProfile;
        dashboardStats: DashboardStats;
    }>;
    getAllATSResults(): Promise<Array<ATSResult>>;
    getAllCareerProfiles(): Promise<Array<CareerProfile>>;
    getAllResumes(): Promise<Array<Resume>>;
    getCareerProfile(user: Principal): Promise<CareerProfile>;
    getDashboardStats(user: Principal): Promise<DashboardStats>;
    getResume(user: Principal): Promise<Resume>;
    getTopReadinessProfiles(limit: bigint): Promise<Array<CareerProfile>>;
    saveATSResult(result: ATSResult): Promise<void>;
    saveCareerProfile(profile: CareerProfile): Promise<void>;
    saveFullProfile(resume: Resume, ats: ATSResult, profile: CareerProfile): Promise<void>;
    saveResume(resume: Resume): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteAllUserData(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllUserData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllUserData(arg0);
            return result;
        }
    }
    async getATSResult(arg0: Principal): Promise<ATSResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getATSResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getATSResult(arg0);
            return result;
        }
    }
    async getAggregatedStats(arg0: Principal): Promise<{
        ats: ATSResult;
        resume: Resume;
        careerProfile: CareerProfile;
        dashboardStats: DashboardStats;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregatedStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregatedStats(arg0);
            return result;
        }
    }
    async getAllATSResults(): Promise<Array<ATSResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllATSResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllATSResults();
            return result;
        }
    }
    async getAllCareerProfiles(): Promise<Array<CareerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCareerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCareerProfiles();
            return result;
        }
    }
    async getAllResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResumes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResumes();
            return result;
        }
    }
    async getCareerProfile(arg0: Principal): Promise<CareerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerProfile(arg0);
            return result;
        }
    }
    async getDashboardStats(arg0: Principal): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getResume(arg0: Principal): Promise<Resume> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return result;
        }
    }
    async getTopReadinessProfiles(arg0: bigint): Promise<Array<CareerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopReadinessProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopReadinessProfiles(arg0);
            return result;
        }
    }
    async saveATSResult(arg0: ATSResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveATSResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveATSResult(arg0);
            return result;
        }
    }
    async saveCareerProfile(arg0: CareerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCareerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCareerProfile(arg0);
            return result;
        }
    }
    async saveFullProfile(arg0: Resume, arg1: ATSResult, arg2: CareerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFullProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFullProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async saveResume(arg0: Resume): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveResume(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
